### ANN Regression

In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
data =pd.read_csv("dataset/Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data = data.drop(["RowNumber","CustomerId","Surname"],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
gender = LabelEncoder()
data["Gender"] = gender.fit_transform(data["Gender"])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [5]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder()
geo_encoder= onehot_encoder.fit_transform(data[["Geography"]])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [6]:
onehot_encoder.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder.get_feature_names_out(["Geography"]))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [8]:
data = pd.concat([data.drop('Geography', axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:

X = data.drop("EstimatedSalary",axis=1)
y = data["EstimatedSalary"]

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
# save the encoders and scalers
with open("models/reg_label_encoder_gender.pkl","wb") as f:
    pickle.dump(gender,f)

with open("models/reg_onehot_encoder_geo.pkl","wb") as f:
    pickle.dump(onehot_encoder,f)

with open("models/reg_scaler.pkl","wb") as f:
    pickle.dump(scaler,f)

In [13]:
### ANN Regression

import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [14]:
# build our ANN model 
model = Sequential([
    Dense(64,activation="relu",input_shape=(X_train.shape[1],)), # first hidden layer HL1 connects with input layer
    Dense(32,activation="relu"), # second hidden layer HL2 connects with HL1
    Dense(1) # output layer

])

# compile the model 
model.compile(optimizer="adam",loss="mean_absolute_error",metrics=["mae"])

model.summary()

d:\Udemy_Generative_AI_course\Enterprise_AI_Engineer_RoadMap\02-Machine_Learning_For_NLP\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [21]:
# setup early stopping
early_stop = EarlyStopping(monitor="val_loss",patience=10, restore_best_weights=True)

In [17]:
## train the model 
history = model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[tensorboard_callback,early_stop])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 9s 14ms/step - loss: 100363.7109 - mae: 100363.7109 - val_loss: 98452.8906 - val_mae: 98452.8906
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 99364.0391 - mae: 99364.0391 - val_loss: 96421.9062 - val_mae: 96421.9062
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 95817.0156 - mae: 95817.0156 - val_loss: 91198.3281 - val_mae: 91198.3281
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 88889.2344 - mae: 88889.2344 - val_loss: 82770.4375 - val_mae: 82770.4375
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 79272.5156 - mae: 79272.5156 - val_loss: 72717.0156 - val_mae: 72717.0156
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 69001.0312 - mae: 69001.0312 - val_loss: 63221.7852 - val_mae: 63221.7852
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 60336.0703 - mae: 60336.0703 - val_loss: 56396.6562 - val_mae: 56396.6562
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 54679.9922 - mae: 54679.9922 - val_loss: 52605.5039 - val_mae: 52605.5039
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51787.2656 - mae: 51787.2656 - val_loss: 51145.5469 - val_mae: 51145.5469
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50688.6523 - mae: 50688.6523 - val_loss: 50721.3203 - val_mae: 50721.3203
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 50307.8867 - mae: 50307.8867 - val_loss: 50616.0781 - val_mae: 50616.0781
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50167.8516 - mae: 50167.8516 - val_loss: 50566.8438 - val_mae: 50566.8438
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50091.0586 - mae: 50091.0586 - val_loss: 50540.9766 - val_mae: 50540.9766
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 50033.3945 - mae: 50033.3945 - val_loss: 50512.6562 - val_mae: 50512.6562
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49985.9336 - mae: 49985.9336 - val_loss: 50479.6758 - val_mae: 50479.6758
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49943.0977 - mae: 49943.0977 - val_loss: 50457.3984 - val_mae: 50457.3984
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49909.0586 - mae: 49909.0586 - val_loss: 50441.1289 - val_mae: 50441.1289
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49870.9102 - mae: 49870.9102 - val_loss: 50419.2773 - val_mae: 50419.2773
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49843.8008 - mae: 49843.8008 - val_loss: 50418.0664 - val_mae: 50418.0664
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 49823.2578 - mae: 49823.2578 - val_loss: 50402.3008 - val_mae: 50402.3008
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49794.9453 - mae: 49794.9453 - val_loss: 50392.7266 - val_mae: 50392.7266
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49777.8750 - mae: 49777.8750 - val_loss: 50373.2852 - val_mae: 50373.2852
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49751.5625 - mae: 49751.5625 - val_loss: 50381.3242 - val_mae: 50381.3242
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49733.8672 - mae: 49733.8672 - val_loss: 50373.2773 - val_mae: 50373.2773
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49709.0898 - mae: 49709.0898 - val_loss: 50358.1836 - val_mae: 50358.1836
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49695.8711 - mae: 49695.8711 - val_loss: 50365.4023 - val_mae: 50365.4023
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49683.0078 - mae: 49683.0078 - val_loss: 50363.1641 - val_mae: 50363.1641
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49663.0273 - mae: 49663.0273 - val_loss: 50357.1328 - val_mae: 50357.1328
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49651.6836 - mae: 49651.6836 - val_loss: 50359.9805 - val_mae: 50359.9805
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49640.7930 - mae: 49640.7930 - val_loss: 50354.9805 - val_mae: 50354.9805
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49624.1367 - mae: 49624.1367 - val_loss: 50362.0273 - val_mae: 50362.0273
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49614.4062 - mae: 49614.4062 - val_loss: 50356.4844 - val_mae: 50356.4844
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49605.6484 - mae: 49605.6484 - val_loss: 50367.4141 - val_mae: 50367.4141
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 49589.2227 - mae: 49589.2227 - val_loss: 50349.4219 - val_mae: 50349.4219
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49580.1953 - mae: 49580.1953 - val_loss: 50341.2656 - val_mae: 50341.2656
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 49568.8398 - mae: 49568.8398 - val_loss: 50343.6133 - val_mae: 50343.6133
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49559.1406 - mae: 49559.1406 - val_loss: 50354.9336 - val_mae: 50354.9336
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49555.1523 - mae: 49555.1523 - val_loss: 50345.4727 - val_mae: 50345.4727
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49538.1289 - mae: 49538.1289 - val_loss: 50353.6875 - val_mae: 50353.6875
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49527.5781 - mae: 49527.5781 - val_loss: 50348.3555 - val_mae: 50348.3555
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49521.6055 - mae: 49521.6055 - val_loss: 50356.3242 - val_mae: 50356.3242
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49511.9609 - mae: 49511.9609 - val_loss: 50343.2852 - val_mae: 50343.2852
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49503.7812 - mae: 49503.7812 - val_loss: 50346.4961 - val_mae: 50346.4961
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49497.3164 - mae: 49497.3164 - val_loss: 50363.4297 - val_mae: 50363.4297
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 49489.3008 - mae: 49489.3008 - val_loss: 50356.0156 - val_mae: 50356.0156

In [18]:
model.save("models/regression_ann_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [19]:
# Load Tensorboard Extension
%load_ext tensorboard

In [23]:
%tensorboard --logdir regessionlogs/fit/

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\Udemy_Generative_AI_course\Enterprise_AI_Engineer_RoadMap\02-Machine_Learning_For_NLP\.venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
    from tensorboard.main import run_main
  File "D:\Udemy_Generative_AI_course\Enterprise_AI_Engineer_RoadMap\02-Machine_Learning_For_NLP\.venv\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "D:\Udemy_Generative_AI_course\Enterprise_AI_Engineer_RoadMap\02-Machine_Learning_For_NLP\.venv\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [24]:
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Test Loss: {test_loss:.4f}")
print(f"Test MAE: {test_mae:.4f}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50341.2656 - mae: 50341.2656
Test Loss: 50341.2656
Test MAE: 50341.2656